"""empty message

Revision ID: 06bccdb0b962
Revises: bd4d7bb94399
Create Date: 2018-06-20 15:54:12.484448

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06bccdb0b962'
down_revision = 'bd4d7bb94399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defect', sa.Column('eliminated', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('defect', 'eliminated')
    # ### end Alembic commands ###
