"""empty message

Revision ID: 7b15121c2e78
Revises: 4a0ad0417c24
Create Date: 2018-06-27 16:59:32.651773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b15121c2e78'
down_revision = '4a0ad0417c24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defect', sa.Column('eliminated_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('defect', 'eliminated_description')
    # ### end Alembic commands ###
