"""empty message

Revision ID: bd4d7bb94399
Revises: 1c50761eb6c9
Create Date: 2018-06-20 15:50:39.908217

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd4d7bb94399'
down_revision = '1c50761eb6c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('defect', sa.Column('taken_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'defect', 'user', ['taken_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'defect', type_='foreignkey')
    op.drop_column('defect', 'taken_user_id')
    # ### end Alembic commands ###
