"""empty message

Revision ID: f4c20716c888
Revises: 06bccdb0b962
Create Date: 2018-06-20 16:01:18.617139

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4c20716c888'
down_revision = '06bccdb0b962'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('defect', 'eliminated',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('defect', 'taken_user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('defect', 'taken_user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('defect', 'eliminated',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
